# RESUMO SEMANA 05

### Bibliotecas Usadas
* Numpy = %pip install -q numpy
* Pandas = %pip install -q pandas

### Importação e Leitura Base

In [9]:
import numpy as np
import pandas as pd
from IPython.display import display

vendas = pd.read_csv("dataset/vendas_papelaria.csv")
display(vendas.head())

,produto,categoria,mes,preco_unitario,quantidade_vendida
0,Caderno,Papelaria,Jan,12.5,30
1,Caderno,Papelaria,Fev,12.5,45
2,Caderno,Papelaria,Mar,12.5,28
3,Caderno,Papelaria,Abr,12.5,50
4,Lapis,Papelaria,Jan,2.0,80


**np.array** = Transforma uma lista em array.

In [ ]:
lista = [1, 2, 3, 4, 5]
print(lista)

lista = (np.array(lista)) * 10
print(lista)

[1, 2, 3, 4, 5]
[10 20 30 40 50]


### Tabela "vendas"



**from IPython.display import display** = Serve para importar o display para o código.

**display(vendas)** = Imprime uma tabela com as informações da tabela vendas

**.shape** = Serve para mostrar a quantidade de linhas e colunas da tabela:
> print(vendas.shape)
>> saída: (24,5)

**.head()** = Serve para mostrar as 5 primeiras linhas da tabela:
> print(vendas.head())

**.describe()** = Serve para criar um resumo estatístico das colunas numéricas de um DataFrame
> print(vendas.describe())
>> saídas:
>>> count - Quantidade de valores preenchidos.

>>> mean - média

>>> std - É o desvio padrão. Mostra o quanto os valores variam em relação à média.

>>>> std pequeno → dados parecidos

>>>> std grande → dados muito diferentes

>>> min - Menor valor.

>>> 25% - 1º quartil. Significa que 25% dos valores são menores ou iguais a esse número.

>>> 50% - É a mediana. Muita gente confunde com média.

>>> 75% - 3º quartil. Significa que 75% dos valores são menores ou iguais a esse número.

>>> max - Maior valor.

**.info()** = Serve para visualizar um resumo das informações, mostrando o tipo da coluna e quantidade de informações preenchidas (avaliar casos vazios)

**.loc()** = Usa o nome da coluna para consultar.
> print(vendas.loc[0,"produto"]) #linha 0, coluna "produto"

**.iloc[]** = Usa a posição e não sabe o noma coluna.
> print(vendas.loc[0,0])  #linha 0, coluna 0

**filtro** = Serve para criar um filtro dentro de uma coluna e regra estabelecida. Criando uma variavel para isso:
> mais_vendidos = vendas[vendas["quantidade_vendido"] > 40]
> print(mais_vendidos)

**.groupby()** = Serve para agrupar conforme regra estabelecida.
> display(vendas.groupby("categoria")["preco_unitario"].mean())

**sort_values()** = Reordena a ordem solicitado. Ascending True ordem crescente ou A-Z; Ascending False ordem decresente ou Z-A.
> display(preco_medio_por_categoria.sort_values(ascending=False))

**drop_duplacates()** = Remover informações duplicados no df

## NumPy arrays
Serve para transformar um lista em array, facilitando operações matemáticas sem a utilização do for:

In [13]:
import numpy as np

precos_lista = [12.5, 2.0, 3.5]
precos_array = np.array(precos_lista)

print(type(precos_lista))
print((precos_lista))

print()
print(type(precos_array))
print((precos_array))

<class 'list'>
[12.5, 2.0, 3.5]

<class 'numpy.ndarray'>
[12.5  2.   3.5]


### Fatiando um array (slice)
Existe a possibilidade de separar as informações do array:

In [3]:
import numpy as np
precos_array = np.array([12.5, 2.0, 3.5, 6.0, 150.0])

print(precos_array[1:4])   # índices 1, 2 e 3 -- NÃO inclui o índice 4
print(precos_array[:3])    # do início até o índice 3 (exclusive) -- os 3 primeiros
print(precos_array[3:])    # do índice 3 até o final

[2.  3.5 6. ]
[12.5  2.   3.5]
[  6. 150.]


## Pandas: Series e DataFrame
| Estrutura | O que é |
|---|---|
| Series | Uma única coluna de dados, com índice|
| DataFrame | Uma tabela completa, com várias colunas (Series juntas)|

In [ ]:
precos_series = vendas["preco_unitario"]          # Series
precos_dataframe = vendas[["preco_unitario"]]      # DataFrame (mantém a estrutura de tabela)

Obs.:
Colchete duplo = mantém a estrutura de tabela. Devolve um DataFrame.

# Exercícios

## Exercício 1
Crie um array NumPy com 6+ números e teste 3 fatiamentos diferentes ([:3], [3:], [2:5]).

In [14]:
import numpy as np

numeros = np.array([10, 20, 30, 40, 50, 60, 70])

print("Array completo:")
print(numeros)

print("\nPrimeiros 3 valores:")
print(numeros[:3])

print("\nDo índice 3 até o final:")
print(numeros[3:])

print("\nDo índice 2 até o 4:")
print(numeros[2:5])

Array completo:
[10 20 30 40 50 60 70]

Primeiros 3 valores:
[10 20 30]

Do índice 3 até o final:
[40 50 60 70]

Do índice 2 até o 4:
[30 40 50]


## Exercício 2
Leia vendas_papelaria.csv com Pandas, use groupby para calcular a receita total por categoria e ordene com sort_values.

In [15]:
import pandas as pd

# Lendo o arquivo CSV
vendas = pd.read_csv("dataset/vendas_papelaria.csv")

# Criando a coluna receita
vendas["receita"] = (
    vendas["preco_unitario"] * vendas["quantidade_vendida"]
)

# Calculando a receita total por categoria
receita_por_categoria = (
    vendas.groupby("categoria")["receita"]
    .sum()
    .sort_values(ascending=False)
)

print(receita_por_categoria)

categoria
Acessorios    5890.0
Papelaria     3855.0
Name: receita, dtype: float64


## Exercício 3
Extraia uma coluna numérica com .to_numpy() e confirme que np.mean() sobre o array bate com .mean() direto na coluna do Pandas.

In [16]:
import pandas as pd
import numpy as np

# Lendo o arquivo
vendas = pd.read_csv("dataset/vendas_papelaria.csv")

# Extraindo uma coluna como array NumPy
precos_array = vendas["preco_unitario"].to_numpy()

# Média usando NumPy
media_numpy = np.mean(precos_array)

# Média usando Pandas
media_pandas = vendas["preco_unitario"].mean()

print(f"Média via NumPy: {media_numpy:.2f}")
print(f"Média via Pandas: {media_pandas:.2f}")

# Confirmação
print("\nAs médias são iguais?")
print(media_numpy == media_pandas)

Média via NumPy: 34.83
Média via Pandas: 34.83

As médias são iguais?
True
